# Generated by Django 5.2.5 on 2025-09-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencysettings',
            name='sos_to_usd_rate',
            field=models.DecimalField(decimal_places=6, default=0.000125, max_digits=10, verbose_name='SOS to USD Exchange Rate'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_debt_sos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_debt_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='amount_sos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('SOS', 'Somaliland Shilling')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid_sos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_paid_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='debt_amount_sos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='debt_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount_sos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SALE_CREATED', 'Sale Created'), ('INVENTORY_ADJUSTED', 'Inventory Adjusted'), ('DEBT_PAID', 'Debt Payment'), ('DEBT_ADDED', 'Debt Added'), ('STAFF_ADDED', 'Staff Added'), ('STAFF_UPDATED', 'Staff Updated'), ('STAFF_DEACTIVATED', 'Staff Deactivated'), ('CUSTOMER_ADDED', 'Customer Added'), ('CURRENCY_UPDATED', 'Currency Rate Updated'), ('create_staff', 'Staff Created')], max_length=50),
        ),
    ]
