# Generated by Django 5.2.5 on 2025-09-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_currencysettings_sos_to_usd_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="total_debt_sos",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="total_debt_usd",
        ),
        migrations.RemoveField(
            model_name="debtpayment",
            name="amount_sos",
        ),
        migrations.RemoveField(
            model_name="debtpayment",
            name="amount_usd",
        ),
        migrations.RemoveField(
            model_name="debtpayment",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="amount_paid_sos",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="amount_paid_usd",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="debt_amount_sos",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="debt_amount_usd",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="total_amount_sos",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="total_amount_usd",
        ),
        migrations.AddField(
            model_name="debtpayment",
            name="original_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Original payment amount in original currency",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="debtpayment",
            name="original_currency",
            field=models.CharField(
                choices=[("USD", "US Dollar"), ("SOS", "Somaliland Shilling")],
                default="USD",
                help_text="Original payment currency",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="original_amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Original amount paid in original currency",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="original_currency",
            field=models.CharField(
                choices=[("USD", "US Dollar"), ("SOS", "Somaliland Shilling")],
                default="USD",
                help_text="Original transaction currency",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="original_total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Original total amount in original currency",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="total_debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total debt in USD",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="debtpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Payment amount in USD", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount paid in USD",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="debt_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Debt amount in USD",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Total amount in USD", max_digits=10
            ),
        ),
    ]
