# Generated by Django 5.2.5 on 2025-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_currency_standardization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debtpayment",
            name="original_currency",
            field=models.CharField(
                choices=[("USD", "US Dollar"), ("SOS", "Somaliland Shilling")],
                default="SOS",
                help_text="Original payment currency",
                max_length=3,
            ),
        ),
    ]
