# Generated by Django 5.2.5 on 2025-09-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_debtpayment_original_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount paid in SOS",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="debt_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Debt amount in SOS",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Total amount in SOS", max_digits=10
            ),
        ),
    ]
