# Generated by Django 5.2.5 on 2025-09-05 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_sos_base_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="total_debt",
            new_name="total_debt_usd",
        ),
        migrations.AddField(
            model_name="customer",
            name="total_debt_sos",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total debt in SOS",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="DebtPaymentSOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount in SOS",
                        max_digits=10,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SOS Debt Payment",
                "verbose_name_plural": "SOS Debt Payments",
            },
        ),
        migrations.CreateModel(
            name="DebtPaymentUSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount in USD",
                        max_digits=10,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "USD Debt Payment",
                "verbose_name_plural": "USD Debt Payments",
            },
        ),
        migrations.CreateModel(
            name="SaleSOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount in SOS", max_digits=10
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount paid in SOS",
                        max_digits=10,
                    ),
                ),
                (
                    "debt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Debt amount in SOS",
                        max_digits=10,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SOS Sale",
                "verbose_name_plural": "SOS Sales",
            },
        ),
        migrations.CreateModel(
            name="SaleItemSOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Unit price in SOS", max_digits=10
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Total price in SOS", max_digits=10
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.salesos",
                    ),
                ),
            ],
            options={
                "verbose_name": "SOS Sale Item",
                "verbose_name_plural": "SOS Sale Items",
            },
        ),
        migrations.CreateModel(
            name="SaleUSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount in USD", max_digits=10
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount paid in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "debt_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Debt amount in USD",
                        max_digits=10,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "USD Sale",
                "verbose_name_plural": "USD Sales",
            },
        ),
        migrations.CreateModel(
            name="SaleItemUSD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Unit price in USD", max_digits=10
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Total price in USD", max_digits=10
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.saleusd",
                    ),
                ),
            ],
            options={
                "verbose_name": "USD Sale Item",
                "verbose_name_plural": "USD Sale Items",
            },
        ),
    ]
