# Generated by Django 5.2.5 on 2025-09-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_dual_currency_tables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="original_amount_paid",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="original_currency",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="original_total_amount",
        ),
        migrations.AlterField(
            model_name="sale",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount paid in original currency",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="debt_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Debt amount in original currency",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total amount in original currency",
                max_digits=10,
            ),
        ),
    ]
