# Generated by Django 5.2.5 on 2025-09-11 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sale_original_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SALE_CREATED', 'Sale Created'), ('INVENTORY_ADJUSTED', 'Inventory Adjusted'), ('DEBT_PAID', 'Debt Payment'), ('DEBT_ADDED', 'Debt Added'), ('DEBT_CORRECTED', 'Debt Corrected'), ('DEBT_MANUALLY_ADJUSTED', 'Debt Manually Adjusted'), ('STAFF_ADDED', 'Staff Added'), ('STAFF_UPDATED', 'Staff Updated'), ('STAFF_DEACTIVATED', 'Staff Deactivated'), ('CUSTOMER_ADDED', 'Customer Added'), ('CURRENCY_UPDATED', 'Currency Rate Updated'), ('create_staff', 'Staff Created')], max_length=50),
        ),
        migrations.CreateModel(
            name='DebtCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('SOS', 'Somaliland Shilling')], max_length=3)),
                ('old_debt_amount', models.DecimalField(decimal_places=2, help_text='Previous debt amount', max_digits=10)),
                ('new_debt_amount', models.DecimalField(decimal_places=2, help_text='New debt amount', max_digits=10)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, help_text='Amount of adjustment (positive or negative)', max_digits=10)),
                ('reason', models.TextField(help_text='Reason for the debt correction')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_corrections', to='core.customer')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debt Correction',
                'verbose_name_plural': 'Debt Corrections',
                'ordering': ['-date_created'],
            },
        ),
    ]
