# Generated by Django 5.2.5 on 2025-09-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_auditlog_action_debtcorrection'),
    ]

    operations = [
    ]
