# Generated by Django 5.2.5 on 2025-09-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250911_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesos',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount in SOS', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleusd',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount in USD', max_digits=10),
        ),
    ]
