# Generated by Django 5.2.5 on 2025-09-11 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_salesos_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='related_sale_sos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salesos'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='related_sale_usd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.saleusd'),
        ),
    ]
