# Generated by Django 5.2.5 on 2026-01-15 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencysettings',
            name='etb_to_usd_rate',
            field=models.DecimalField(decimal_places=6, default=0.01, max_digits=10, verbose_name='ETB to USD Exchange Rate'),
        ),
        migrations.AddField(
            model_name='currencysettings',
            name='usd_to_etb_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='USD to ETB Exchange Rate'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_debt_etb',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total debt in ETB', max_digits=10),
        ),
        migrations.AlterField(
            model_name='debtcorrection',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('SOS', 'Somaliland Shilling'), ('ETB', 'Ethiopian Birr')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sale',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('SOS', 'Somaliland Shilling'), ('ETB', 'Ethiopian Birr')], default='USD', max_length=3),
        ),
        migrations.CreateModel(
            name='SaleETB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount in ETB', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid in ETB', max_digits=10)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Debt amount in ETB', max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ETB Sale',
                'verbose_name_plural': 'ETB Sales',
            },
        ),
        migrations.CreateModel(
            name='SaleItemETB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price in ETB', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price in ETB', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.saleetb')),
            ],
            options={
                'verbose_name': 'ETB Sale Item',
                'verbose_name_plural': 'ETB Sale Items',
            },
        ),
    ]
