# Generated by Django 5.2.5 on 2026-01-15 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_currencysettings_etb_to_usd_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='related_sale_etb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.saleetb'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='original_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('SOS', 'Somaliland Shilling'), ('ETB', 'Ethiopian Birr')], default='SOS', help_text='Original payment currency', max_length=3),
        ),
        migrations.CreateModel(
            name='DebtPaymentETB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in ETB', max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ETB Debt Payment',
                'verbose_name_plural': 'ETB Debt Payments',
            },
        ),
    ]
