# Generated by Django 5.2.5 on 2026-01-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_inventorylog_related_sale_etb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleetb',
            name='exchange_rate_at_sale',
            field=models.DecimalField(decimal_places=2, default=185.0, help_text='USD to ETB exchange rate at time of sale', max_digits=10),
        ),
    ]
