# Generated by Django 5.2.5 on 2026-01-17 19:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_exchange_rate_to_sale_etb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleetb',
            name='exchange_rate_at_sale',
            field=models.DecimalField(decimal_places=2, default=185.0, help_text='USD to ETB exchange rate at time of sale', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
