# Generated by Django 5.2.5 on 2026-01-17 19:10

from django.db import migrations


def migrate_staff_to_user(apps, schema_editor):
    # Get models
    SaleUSD = apps.get_model('core', 'SaleUSD')
    SaleSOS = apps.get_model('core', 'SaleSOS')
    SaleETB = apps.get_model('core', 'SaleETB')
    Sale = apps.get_model('core', 'Sale')
    
    # Migrate SaleUSD
    for sale in SaleUSD.objects.all():
        if sale.staff_member_id:
            sale.user_id = sale.staff_member_id
            sale.save()
            
    # Migrate SaleSOS
    for sale in SaleSOS.objects.all():
        if sale.staff_member_id:
            sale.user_id = sale.staff_member_id
            sale.save()
            
    # Migrate SaleETB
    for sale in SaleETB.objects.all():
        if sale.staff_member_id:
            sale.user_id = sale.staff_member_id
            sale.save()

    # Migrate Legacy Sale
    for sale in Sale.objects.all():
        if sale.staff_member_id:
            sale.user_id = sale.staff_member_id
            sale.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_user_remove_staff_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_staff_to_user),
    ]
