# Generated by Django 5.2.5 on 2026-01-17 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_migrate_staff_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='staff_member',
        ),
        migrations.RemoveField(
            model_name='saleetb',
            name='staff_member',
        ),
        migrations.RemoveField(
            model_name='saleusd',
            name='staff_member',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_restock',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_sell',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active_staff',
        ),
        migrations.AddField(
            model_name='debtcorrection',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_debt_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtpaymentetb',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etb_debt_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtpaymentsos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_debt_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtpaymentusd',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usd_debt_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_sale_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applies only to METER products', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_unit',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('METER', 'Meter')], default='UNIT', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleetb',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etb_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleusd',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usd_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='debtcorrection',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_debt_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_legacy_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debtpaymentetb',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_etb_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debtpaymentsos',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_sos_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debtpaymentusd',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_usd_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_inventory_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitemetb',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitemsos',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitemusd',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
