# Generated by Django 5.2.5 on 2026-01-17 19:17

from django.db import migrations



def migrate_logs_and_payments(apps, schema_editor):
    InventoryLog = apps.get_model('core', 'InventoryLog')
    DebtPaymentUSD = apps.get_model('core', 'DebtPaymentUSD')
    DebtPaymentSOS = apps.get_model('core', 'DebtPaymentSOS')
    DebtPaymentETB = apps.get_model('core', 'DebtPaymentETB')
    DebtPayment = apps.get_model('core', 'DebtPayment')
    DebtCorrection = apps.get_model('core', 'DebtCorrection')
    
    # Migrate InventoryLog
    for log in InventoryLog.objects.all():
        if log.staff_member_id:
            log.user_id = log.staff_member_id
            log.save()
            
    # Migrate DebtPaymentUSD
    for payment in DebtPaymentUSD.objects.all():
        if payment.staff_member_id:
            payment.user_id = payment.staff_member_id
            payment.save()
            
    # Migrate DebtPaymentSOS
    for payment in DebtPaymentSOS.objects.all():
        if payment.staff_member_id:
            payment.user_id = payment.staff_member_id
            payment.save()

    # Migrate DebtPaymentETB
    for payment in DebtPaymentETB.objects.all():
        if payment.staff_member_id:
            payment.user_id = payment.staff_member_id
            payment.save()

    # Migrate Legacy DebtPayment
    for payment in DebtPayment.objects.all():
        if payment.staff_member_id:
            payment.user_id = payment.staff_member_id
            payment.save()

    # Migrate DebtCorrection
    for correction in DebtCorrection.objects.all():
        if correction.staff_member_id:
            correction.user_id = correction.staff_member_id
            correction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_user_to_logging_models'),
    ]

    operations = [
        migrations.RunPython(migrate_logs_and_payments),
    ]
