# Generated by Django 5.2.5 on 2026-01-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_migrate_logging_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtcorrection',
            name='staff_member',
        ),
        migrations.RemoveField(
            model_name='debtpayment',
            name='staff_member',
        ),
        migrations.RemoveField(
            model_name='debtpaymentetb',
            name='staff_member',
        ),
        migrations.RemoveField(
            model_name='debtpaymentsos',
            name='staff_member',
        ),
        migrations.RemoveField(
            model_name='debtpaymentusd',
            name='staff_member',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='staff_member',
        ),
    ]
