# Generated by Django 5.2.5 on 2026-01-17 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_staff_member_fields_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesos',
            name='staff_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_sales_legacy', to=settings.AUTH_USER_MODEL),
        ),
    ]
