# Generated by Django 5.2.5 on 2026-01-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_migrate_salesos_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesos',
            name='staff_member',
        ),
    ]
