# Generated by Django 5.2.5 on 2026-01-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_salesos_staff_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='new_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='old_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='quantity_change',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
