# Generated by Django 5.2.5 on 2026-01-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_inventorylog_new_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitemetb',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity bought', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitemsos',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity bought', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitemusd',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity bought', max_digits=10),
        ),
    ]
