# Generated by Django 5.2.5 on 2026-01-22 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_saleitemetb_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Admin user who performed the action (null for anonymous/system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Optional - allows anonymous sales', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional - admin user who created the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleetb',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Optional - allows anonymous sales', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='saleetb',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional - admin user who created the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etb_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesos',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Optional - allows anonymous sales', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='salesos',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional - admin user who created the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleusd',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Optional - allows anonymous sales', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='saleusd',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Optional - admin user who created the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usd_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
