# Generated by Django 5.2.5 on 2026-01-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_user_options_remove_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SALE_CREATED', 'Sale Created'), ('INVENTORY_ADJUSTED', 'Inventory Adjusted'), ('DEBT_PAID', 'Debt Payment'), ('DEBT_ADDED', 'Debt Added'), ('DEBT_CORRECTED', 'Debt Corrected'), ('DEBT_MANUALLY_ADJUSTED', 'Debt Manually Adjusted'), ('CUSTOMER_ADDED', 'Customer Added'), ('CURRENCY_UPDATED', 'Currency Rate Updated')], max_length=50),
        ),
    ]
